#!/usr/bin/env python

import rospy
import sys
import os.path
from infobot_topo_msgs.srv import ProcessCurrentMetricMap
from infobot_topo_msgs.msg import MetricMapTransform
from geometry_msgs.msg import Pose2D


# -----------------------------------------------------------------------------
def main():
    rospy.init_node("topo_mapping_create_new_map")

    # Args
    if (len(sys.argv) <= 3):
        print("Usage: %s <rel_x> <rel_y> <rel_theta> " % os.path.basename(sys.argv[0]))
        sys.exit(1)
    transform = MetricMapTransform()
    # FIX: Fill the thing in!
    transforms = [transform]

    # Call service
    rospy.wait_for_service("/topo_mapping/process_current_metric_map")
    try:
        process_current_metric_map = rospy.ServiceProxy(
            "/topo_mapping/process_current_metric_map", ProcessCurrentMetricMap)
        process_current_metric_map(transforms, Pose2D())
    except rospy.ServiceException, e:
        print "Service call failed: %s" % e


# -----------------------------------------------------------------------------
if __name__ == "__main__":
    main()
