uint8 SURFACE = 0
uint8 HEIGHT = 1

uint8 pmap_to_octomap_mode

string pmap_filename
string pmap_frame_id
string octomap_filename
string octomap_frame_id
string topomap_filename
string topomap_frame_id
---
string img_filename
---
geometry_msgs/Pose[] poses
float64[] vis_values
