#!/usr/bin/python

import rospy
import actionlib
import sys
import tf
from move_base_msgs.msg import *


# ------------------------------------------------------------
def main():
    rospy.init_node("move_base_send_goal")

    # Get params
    xp = float(sys.argv[1])
    yp = float(sys.argv[2])
    th = float(sys.argv[3])

    # Send goal
    action_client = actionlib.SimpleActionClient("move_base", MoveBaseAction)
    action_client.wait_for_server()
    goal = MoveBaseGoal()
    goal.target_pose.header.stamp = rospy.get_rostime()
    goal.target_pose.header.frame_id = "map"
    goal.target_pose.pose.position.x = xp
    goal.target_pose.pose.position.y = yp
    goal.target_pose.pose.position.z = 0.0
    quaternion = tf.transformations.quaternion_from_euler(0, 0, th)
    goal.target_pose.pose.orientation.x = quaternion[0]
    goal.target_pose.pose.orientation.y = quaternion[1]
    goal.target_pose.pose.orientation.z = quaternion[2]
    goal.target_pose.pose.orientation.w = quaternion[3]
    action_client.send_goal(goal)
    action_client.wait_for_result()


# ------------------------------------------------------------
if __name__ == '__main__':
    main()
