#!/usr/bin/env python

import rospy

from test_utils import *

if __name__ == "__main__":

    # inputs
    pmap_filename = "sim-simple-room1.yaml"
    octomap_filename = "sim-simple-model.bt"
    # pmap_filename = "real-floor4-CSE491.yaml"
    # octomap_filename = "real-floor4-model.bt"


    x = 0.0
    y = 0.0
    theta = 0.0
    mode = ComputeVisibilityValueRequest.HEIGHT

    # main
    rospy.init_node("test_compute_vis_val", anonymous=True)

    publish_pmap_octomap(pmap_filename, octomap_filename)

    print call_compute_vis_value_srv_xytheta(x, y, theta, mode)
