#!/usr/bin/env python

import rospy

from test_utils import *

if __name__ == "__main__":

    # inputs
    pmap_filename = "sim-simple-room1.yaml"
    octomap_filename = "sim-simple-model.bt"
    topomap_filename = "sim-simple_corridor-topo.yaml"
    # pmap_filename = "real-floor4-CSE491.yaml"
    # octomap_filename = "real-floor4-model.bt"
    # topomap_filename = "real-floor4-nogo-topo.yaml"

    margin = 2.0
    # margin = 5.0

    mode = ComputeVisibilityValuesRequest.HEIGHT

    # main
    rospy.init_node("test_compute_vis_vals", anonymous=True)

    publish_pmap_octomap_topomap(pmap_filename, octomap_filename, topomap_filename)

    poses = get_poses_from_topomap(topomap_filename)

    poses = apply_pmap_bbx_filter(poses, pmap_filename, margin)

    resp = call_compute_vis_values_srv(poses, ComputeVisibilityValuesRequest.SURFACE)

    max_val = max(resp.vis_values)
    max_index = [i for i, j in enumerate(resp.vis_values) if j == max_val][0]
    max_pose = poses[max_index]
    print resp
    print "max vis_value =", max_val

    call_compute_vis_value_srv(max_pose, mode)
