#!/usr/bin/env python

import rospy

import sys
import os
import numpy as np
import cv2
import rosbag
from cv_bridge import CvBridge
from nav_msgs.msg import Path
from geometry_msgs.msg import Pose
from move_base_msgs.msg import *
from tf.transformations import quaternion_from_euler, euler_from_quaternion
from infobot_find_viewpoint_msgs.srv import *
from infobot_map_msgs.srv import *
from infobot_topo_msgs.srv import *


def call_srv(srv_name, srv_type, srv_args):
    rospy.wait_for_service(srv_name)
    try:
        srv_proxy = rospy.ServiceProxy(srv_name, srv_type)
        return srv_proxy(*srv_args)
    except rospy.ServiceException, e:
        rospy.logerr("Service call failed: %s" % e)
        print srv_args
        return None


def publish_pmap_octomap(pmap_filename, octomap_fiilename):
    rospy.logwarn("IGNORES INPUT pmap_frame_id. Uses \"map\" instead.")
    publish_pmap_resp = call_srv("publish_pmap", PublishProbabilityMap, (pmap_filename, ""))
    if not publish_pmap_resp or not publish_pmap_resp.success:
        return False
    rospy.logwarn("IGNORES INPUT octomap_frame_id. Uses \"map\" instead.")
    publish_octomap_resp = call_srv("publish_octomap", PublishOctomap, (octomap_fiilename, ""))
    if not publish_octomap_resp or not publish_octomap_resp.success:
        return False
    return True


def publish_pmap_octomap_topomap(pmap_filename, octomap_fiilename, topomap_filename):
    publish_pmap_octomap(pmap_filename, octomap_fiilename)
    rospy.logwarn("IGNORES INPUT topomap_frame_id. Uses \"map\" instead.")
    publish_topomap_resp = call_srv("publish_topomap", PublishTopologicalMap, (topomap_filename, ""))
    if not publish_topomap_resp or not publish_topomap_resp.success:
        return False
    return True


def call_compute_vis_value_srv(pose, mode):
    resp = call_srv("compute_vis_value", ComputeVisibilityValue, (
        pose,
        mode,
        "",  # use published pmap_filename
        "",  # use published pmap_frame
        "",  # use published octomap_filename
        ""   # use published octomap_frame
    ))
    return resp


def get_poses_from_topomap(topomap_fiilename, z):
    get_topomap_resp = call_srv("get_topomap", GetTopologicalMap, (topomap_fiilename, ""))
    if not get_topomap_resp:
        return []

    poses = []
    for place in get_topomap_resp.topomap.places:
        for view in place.views:
            pose = Pose()
            pose.position.x = view.pose.x
            pose.position.y = view.pose.y
            pose.position.z = z
            q = quaternion_from_euler(0, 0, view.pose.theta)
            pose.orientation.x = q[0]
            pose.orientation.y = q[1]
            pose.orientation.z = q[2]
            pose.orientation.w = q[3]
            poses.append(pose)

    return poses


def call_compute_vis_values_srv(poses, mode):
    resp = call_srv("compute_vis_values", ComputeVisibilityValues, (
        poses,
        mode,
        "",  # use published pmap_filename
        "",  # use published pmap_frame
        "",  # use published octomap_filename
        ""   # use published octomap_frame
    ))
    return resp


if __name__ == "__main__":
    rospy.init_node("retrospective_query")

    if len(sys.argv) < 8:
        print >> sys.stderr, ("%s <img_filename> <pmap_to_octomap_mode> <pmap_filename> <octomap_filename> "
                              "<topomap_filename> <robotbag_filename> <pathbag_filename>" % rospy.get_name())
        sys.exit(1)

    img_filename = sys.argv[1]
    pmap_to_octomap_mode = int(sys.argv[2])
    pmap_filename = sys.argv[3]
    octomap_filename = sys.argv[4]
    topomap_filename = sys.argv[5]
    robotbag_filename = sys.argv[6]
    pathbag_filename = sys.argv[7]

    camera_trans_z = rospy.get_param("~camera_trans_z", 1.5)
    pose_candidate_min_dist = rospy.get_param("~pose_candidate_min_dist", 0.2)  # in meters
    pose_candidate_min_ang_diff = rospy.get_param("~pose_candidate_min_ang_diff", 20 * np.pi / 180)  # in radians
    camera_topic_name = rospy.get_param("~camera_topic_name", "/prosilica_vga/image_rect_color")
    visualization_on = rospy.get_param("~visualization_on", True)

    # Get poses.
    poses = []
    # publish maps
    if not publish_pmap_octomap_topomap(pmap_filename, octomap_filename, topomap_filename):
        print >> sys.stderr, "Error while publishing maps."
        sys.exit(1)
    # process maps
    poses = get_poses_from_topomap(topomap_filename, camera_trans_z)
    if poses == []:
        print >> sys.stderr, "Error while extracting poses from topomap."
        sys.exit(1)

    # Get path.
    pathbag_filepath = os.path.join(os.path.expanduser("~"), "bags", pathbag_filename)
    if not os.path.isfile(pathbag_filepath):
        print >> sys.stderr, "%s does not exist." % pathbag_filepath
        sys.exit()
    pathbag = rosbag.Bag(pathbag_filepath)
    path = pathbag.read_messages().next()[1]  # topic_name, msg, time
    path_pub = rospy.Publisher("/path", Path, queue_size=10, latch=True)
    path_pub.publish(path)

    # Filter unvisited poses.
    visited_poses = {}
    i = 0
    for pose in poses:
        cands = []
        for pose_stamped in path.poses:
            dist = np.sqrt(np.power(pose_stamped.pose.position.x - pose.position.x, 2) +
                           np.power(pose_stamped.pose.position.y - pose.position.y, 2))
            if dist < pose_candidate_min_dist:
                cands.append(pose_stamped)
        if len(cands) == 0:
            continue

        min_ang_diff = sys.float_info.max
        best_cand = cands[0]
        for cand in cands:
            a1 = euler_from_quaternion([cand.pose.orientation.x,
                                        cand.pose.orientation.y,
                                        cand.pose.orientation.z,
                                        cand.pose.orientation.w])
            a2 = euler_from_quaternion([pose.orientation.x,
                                        pose.orientation.y,
                                        pose.orientation.z,
                                        pose.orientation.w])
            cur_diff = np.sum(np.fabs(np.array(a1) - np.array(a2)))
            if cur_diff < min_ang_diff:
                best_cand = cand
                min_ang_diff = cur_diff
        if min_ang_diff > pose_candidate_min_ang_diff:
            continue

        visited_poses[pose] = best_cand
    if len(visited_poses) == 0:
        print >> sys.stderr, "There are no poses left after filtering."
        sys.exit(1)

    # Compute Visibility.
    compute_vis_vals_resp = call_compute_vis_values_srv(visited_poses.keys(), pmap_to_octomap_mode)
    if not compute_vis_vals_resp:
        sys.exit(1)
    if sum(compute_vis_vals_resp.vis_values) == 0:
        print >> sys.stderr, "vis_values are all zero. Cannot see the requested target."
        sys.exit(1)
    max_vis_val_visited = max(compute_vis_vals_resp.vis_values)
    max_vis_val_visited_index = [
        i for i, j in enumerate(compute_vis_vals_resp.vis_values) if j == max_vis_val_visited][0]
    max_visited_pose = visited_poses.keys()[max_vis_val_visited_index]
    call_compute_vis_value_srv(max_visited_pose, pmap_to_octomap_mode)  # for debugging

    # Get images.
    robotbag_filepath = os.path.join(os.path.expanduser("~"), "bags", robotbag_filename)
    if not os.path.isfile(robotbag_filepath):
        print >> sys.stderr, "%s does not exist." % robotbag_filepath
        sys.exit(1)
    robotbag = rosbag.Bag(robotbag_filepath)

    # Find the image.
    t_max_visited_pose = visited_poses[max_visited_pose].header.stamp
    min_t_diff = None
    image_msg = None
    for topic, msg, t in robotbag.read_messages(topics=[camera_topic_name]):
        t_diff = None
        if t > t_max_visited_pose:
            t_diff = t - t_max_visited_pose
        else:
            t_diff = t_max_visited_pose - t
        if min_t_diff is None or t_diff < min_t_diff:
            min_t_diff = t_diff
            image_msg = msg

    # Save the image.
    bridge = CvBridge()
    cv_image = bridge.imgmsg_to_cv2(image_msg, "bgr8")
    if visualization_on:
        print "Press any key to continue."
        cv2.namedWindow("Best Viewpoint", 1)
        cv2.imshow("Best Viewpoint", cv_image)
        cv2.waitKey()
    try:
        cv2.imwrite(img_filename, cv_image)
    except:
        print >> sys.stderr, "Failed to save image: %s" % img_filename
        sys.exit(1)

    print "Done! result image: %s" % img_filename
    print "Use Ctrl+C to kill the program."
    rospy.spin()
