#!/usr/bin/python

import rospy

import sys

import actionlib
from infobot_find_viewpoint_msgs.msg import *
from infobot_find_viewpoint_msgs.srv import *


if __name__ == "__main__":
    rospy.init_node("find_viewpoint_send_goal", anonymous=True)

    # Get params
    if len(sys.argv) < 5:
        print >> sys.stderr, "send_goal <mode> <pmap_filename> <octomap_filename> <topomap_filename>"
        sys.exit(1)

    mode = int(sys.argv[1])
    pmap_filename = sys.argv[2]
    octomap_filename = sys.argv[3]
    topomap_filename = sys.argv[4]

    # Send goal
    action_client = actionlib.SimpleActionClient("find_viewpoint", FindViewpointAction)
    action_client.wait_for_server()
    goal = FindViewpointGoal()
    goal.pmap_to_octomap_mode = mode
    goal.pmap_filename = pmap_filename
    goal.pmap_frame_id = ""
    goal.octomap_filename = octomap_filename
    goal.octomap_frame_id = ""
    goal.topomap_filename = topomap_filename
    goal.topomap_frame_id = ""

    action_client.send_goal(goal)
    action_client.wait_for_result()

    print "state:", action_client.get_state()
    print "result:", action_client.get_result()
